### ISSUE TITLE
more log filenames

### ISSUE THREAD

**Issue by ATmarked** [stolk/chiaharvestgraph#13]
When setting a different log level, like INFO the logfiles become less dense and there's more files needed to have a full screen view.

Please support more log files than 8
        "debug.log.7",

We keep 15 log files and it only fills the last 2 hours of the display, because not all are being loaded.

**Comment by gschlager** [comment]
I second that request. It would be great if it reads as many log files as needed to fill the 3 days shown.

**Comment by stolk** [comment]
Support for this has been added. See the README section on Environment Variables.
