### ISSUE TITLE
Slowest-Check

### ISSUE THREAD

**Issue by zabbzabb** [stolk/chiaharvestgraph#15]
Hello! Thank you for a wonderful project.
I am interested in the "SLOWEST-CHECK" parameter, what does it affect and is it worth worrying about the low speed?
If so, tell me how you can speed it up.

![Снимок экрана от 2021-05-16 12-00-49](https://user-images.githubusercontent.com/76556159/118391712-701b5880-b63e-11eb-9bba-d85d8e5ebe0f.png)

Please give a detailed description of these two parameters:
AVG-CHECK, SLOWEST-CHECK

Sincerely, Alexander.

**Comment by nmistry** [comment]
These lines of code explain what AVG-CHECK and below that what SLOWEST-CHECK "ok", and "slow" correlate to. 
  
https://github.com/stolk/chiaharvestgraph/blob/1ab6bf1488c632fa351fece66341556df983e6e6/chiaharvestgraph.c#L443-L449

**Comment by graemes** [comment]
Hi,
Shouldn't the q_av descriptions be the same as the q_wo descriptions?  I'd be very happy if my set of hdd's where able to respond in less than 80ms on average but the q_wo descriptions feel more realistic.
