### ISSUE TITLE
Pushover support

### ISSUE THREAD

**Issue by njardus** [stolk/chiaharvestgraph#19]
Suggestion: Add basic Pushover support to send a notification for a certain level of event - a win, for instance.
Swar Plot Manager has it implemented for plotting, albeit in python.

**Comment by stolk** [comment]
Out of scope for this project, which is intended to be minimalist and small enough for quick vetting.

**Comment by njardus** [comment]
Fair enough. Thanks for the reply and the excellent project! 👍
