### ISSUE TITLE
Add xterm as dependency and do autocheck for log INFO level?

### ISSUE THREAD

**Issue by sxiii** [stolk/chiaharvestgraph#25]
Greetings. Tried the software; it's really nice; thanks for writing it.

I however got into this small problem. I had no xterm installed. All my rows were orange all around. Sorry haven't made screenshot at that time but it was perfect light and dark orange stripes. Seemed to strange to me. Also time (AVG-CHECK and Slowest-check) was minus something.

After I installed xterm and re-started the chia, everything is now seems to be working. However, not 100% sure - this might as well be tied to me not turning on INFO level on logs before xterm installation. Maybe add a check that shows "error" or "warning" message to user, unless log is set to INFO; and also add xterm to dependencies if it's really needed?

Thanks anyway!
Den

**Comment by stolk** [comment]
24-bit support is req'd, there is no good test for this.

**Comment by sxiii** [comment]
Yes but maybe add autocheck for log INFO level? :)
