### ISSUE TITLE
stack smashing detected

### ISSUE THREAD

**Issue by marked** [stolk/chiaharvestgraph#26]
If you leave the app running long enough it will die with this error message:
*** stack smashing detected ***: terminated Segmentation fault

Maybe a memory leak?

**Comment by stolk** [comment]
Interesting... could you try to repro with:
```
$ gdb chiaharvestgraph
>>> run ~/.chia/mainnet/log
```

And when it crashes, type
`>>> where`

And report back with any info from the terminal?
Thx!

**Comment by roxleopardo** [comment]
I got this fixed on #38

**Comment by stolk** [comment]
The real issue is still unclear to me, but it did get fixed in commit 9fca9af47730217731f974571958a5ea3ab01a20
