### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by aliyucad** [stolk/chiaharvestgraph#29]
I successfully cloned it to my system, which is ubuntu. When I run the command "make" from the chiaharvestgraph directory, I get the following error:
cc -D_POSIX_C_SOURCE=200809L -std=c99 -Wall -Wno-missing-braces -g -c chiaharvestgraph.c -o chiaharvestgraph.o
make: cc: Command not found
make: *** [Makefile:15: chiaharvestgraph.o] Error 127
Please help me with this issue. Thank you

**Comment by KipiKland** [comment]
you are missing dependencies on building binary.  run "sudo apt install build-essential"
